# Generated by Django 3.0.3 on 2020-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now=True, verbose_name='Post Date')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
